#!/bin/bash

set -e

SITE_DIRECTORY_PATH=~/projects/brianpfeil.com
SITE_CONFIG_FILE_PATH="${SITE_DIRECTORY_PATH}/config.yaml"
POST_DIRECTORY_PATH="${SITE_DIRECTORY_PATH}/content/post"

display_usage() {
    echo -e "site (personal website) tool\n"
    echo -e "USAGE"
    echo -e "\t$ site [COMMAND]\n"
    echo -e "COMMANDS"
    echo -e "\tsite run-local"
    echo -e "\tsite post [-t title]"
    echo -e "\tsite generate-posts-from-repos"
}

if [ $# -le 0 ]; then
    display_usage
    exit 1
fi

if [[ ( $# == "--help") || $# == "-h" ]]; then
    display_usage
    exit 0
fi

PARAMS=""

while (( "$#" )); do
  case "$1" in
    -t|--title)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        TITLE=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -*|--*=)
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *)
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
eval set -- "$PARAMS"

CMD="${1}"

runLocal() {
  pushd "${SITE_DIRECTORY_PATH}"
  make dev &
  popd
  sleep 3
  open "http://localhost:1313"
  echo -e "press any key to stop server ..."
  read REPLY
  cmd='killall "hugo"'
  echo -e "${cmd}\n"
  eval "${cmd}"
}

slugify() {
  echo "$1" | iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | sed -E 's/^-+//g' | sed -E 's/-+$//g' | tr A-Z a-z
}

post() {
  pushd "${SITE_DIRECTORY_PATH}"
  local title="$1"
  local slug=$(slugify "${title}")
  local post_file_directory_path="${POST_DIRECTORY_PATH}/${slug}"
  local post_file_path="${post_file_directory_path}/index.md"

  if [ -d "${post_file_directory_path}" ]; then
      echo "post directory \"${post_file_directory_path}\" exists. please choose a different post name"
      exit 1
  else
    mkdir -p "${post_file_directory_path}"
    mkdir -p "${post_file_directory_path}/images"
  fi

  hugo new "${post_file_path}" --config "${SITE_CONFIG_FILE_PATH}"

  echo -e "\n\npost file created at ${post_file_path}\n\n"
  popd
}

generatePostsFromRepos() {
  pushd "${SITE_DIRECTORY_PATH}/tools/generate-posts"
  go run . -user="pfeilbr" -dest="${POST_DIRECTORY_PATH}" -debug
  popd
}

case "${CMD}" in
run-local)
  runLocal
  ;;
post)
  post "${TITLE}"
  ;;
generate-posts-from-repos)
  generatePostsFromRepos
  ;;
*)
  echo -e "unsupported command \"${CMD}\"\n\n"
  display_usage
  exit 1
  ;;
esac
