#!/usr/bin/env python3
"""Write one page per /learn/ path, in every language: content/learn/<key>.<lang>.md.

    python3 tools/learn-links/path_pages.py           # write
    python3 tools/learn-links/path_pages.py --check   # exit 1 if out of date

Each path (data/learn.json) gets its own URL, /learn/<key>/, so it has its
own title, description, share card and sitemap entry, and a link to "the AI
path" opens on exactly that. The pages are just front matter: title and
description come from the path's i18n strings (learn_path_<key>,
learn_path_blurb_<key>), and layouts/_default/learn.html draws the page with
that path selected. Re-run after adding a path or changing its strings;
`make verify` fails while the files are stale. Pages for paths no longer in
learn.json are deleted. Standard library only.
"""

import json
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data" / "learn.json"
I18N = REPO / "i18n"
OUT = REPO / "content" / "learn"
LANGS = ["en", "zh", "es", "pt", "fr", "de", "it", "ja", "ko"]
DATE = "2026-09-29T00:00:00Z"


def toml_str(s):
    return json.dumps(s, ensure_ascii=False)


def strings(lang):
    t = tomllib.loads((I18N / f"{lang}.toml").read_text())
    return lambda k: (t.get(k) or {}).get("other", "")


def wanted():
    paths = json.loads(DATA.read_text())["paths"]
    files = {}
    for lang in LANGS:
        s = strings(lang)
        suffix = "" if lang == "en" else f".{lang}"
        for i, p in enumerate(paths):
            key = p["key"]
            title, blurb = s(f"learn_path_{key}"), s(f"learn_path_blurb_{key}")
            if not title or not blurb:
                raise SystemExit(f"{lang}: learn_path_{key} / learn_path_blurb_{key} missing or empty")
            files[OUT / f"{key}{suffix}.md"] = (
                "+++\n"
                "# Generated by tools/learn-links/path_pages.py from data/learn.json -- don't edit.\n"
                f"title = {toml_str(title)}\n"
                f"description = {toml_str(blurb)}\n"
                f"date = {DATE}\n"
                f'slug = "{key}"\n'
                'layout = "learn"\n'
                f'learn_path = "{key}"\n'
                f"weight = {i + 1}\n"
                "+++\n")
    return files


def existing():
    return {f for f in OUT.glob("*.md") if not f.name.startswith("_")}


def main(argv=None):
    check = "--check" in (argv or sys.argv[1:])
    want = wanted()
    stale = [f for f, body in want.items() if not f.exists() or f.read_text() != body]
    extra = existing() - set(want)
    if check:
        if stale or extra:
            for f in stale + sorted(extra):
                print(f"out of date: {f.relative_to(REPO)}")
            print("run: python3 tools/learn-links/path_pages.py")
            return 1
        print(f"ok: {len(want)} learn path pages up to date")
        return 0
    for f in stale:
        f.write_text(want[f])
    for f in extra:
        f.unlink()
    print(f"wrote {len(stale)}, removed {len(extra)}, {len(want)} pages in {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
