#!/usr/bin/env python3
"""Write data/music.yaml: my YouTube Music playlists for /music/.

Where the playlists come from:
  mine   every public playlist on the channel in config.json ("channel"),
         minus config "exclude" (id -> why). Discovered from the channel's Playlists
         tab, so a playlist made public on YouTube shows up on the next run
         and one made private drops off.
  saved  the ids in config "saved" -- other people's playlists I saved.
         The library that holds them needs my sign-in, so they are listed
         by hand; this refreshes their titles, owners and track counts and
         drops any that stopped being public.

A playlist is listed only if a stranger can play it: its page loads without
signing in, and the embed /music/ uses reports status OK when fetched with
this site as the referer -- the same answer a visitor's browser gets. That
catches a first track blocked by a rights claim ("Video unavailable"),
which oEmbed and the player API both miss. "exclude" is for playlists that
play but shouldn't be listed.

Track lists come from YouTube Music's own API (the one music.youtube.com
calls), which names artists properly -- "Drake, 21 Savage" rather than a
"DrakeVEVO" channel. top_artists counts every track entry in "mine", so a
song on three playlists counts three times.

Playlist notes are i18n (pl_note_<key>); config "note_keys" maps a
playlist id to its key. A new playlist has no note until one is added.

  python3 tools/music/refresh.py            # fetch and write
  python3 tools/music/refresh.py --dry-run  # fetch and print, write nothing

No sign-in, no API key, standard library only.
"""
import argparse
import collections
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
OUT = ROOT / "data" / "music.yaml"
CONFIG = HERE / "config.json"

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
WEB = {"clientName": "WEB", "clientVersion": "2.20250101.00.00", "hl": "en", "gl": "US"}
REMIX = {"clientName": "WEB_REMIX", "clientVersion": "1.20250101.01.00", "hl": "en", "gl": "US"}
EMBED = "https://www.youtube.com/embed/videoseries?list="
SITE = "https://brianpfeil.com/"  # the embed refuses to say anything without a referer (error 153)
MAX_LOSS = 0.25  # refuse to drop more than this share of listed playlists in one run
RETRIES = 4
MAX_PAGES = 50  # 100 tracks a page; a runaway continuation stops here

HEADER = """\
# GENERATED by tools/music/refresh.py (make music-refresh) -- don't hand-edit.
# Which playlists appear is set in tools/music/config.json.
#
# Playlists from my YouTube Music library (music.youtube.com). Only
# playlists that a stranger can actually play are listed: private ones are
# omitted, and so are ones whose first track refuses to embed.
#
# `id` is the YouTube list id. Cards embed as
# https://www.youtube.com/embed/videoseries?list=<id> and link out to
# https://music.youtube.com/playlist?list=<id>.
"""


# --- HTTP -----------------------------------------------------------------

def fetch(req, read):
    """urlopen with retries: YouTube stalls a read now and then. An HTTP
    error status is an answer, not a stall, so it is raised at once."""
    for attempt in range(RETRIES):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                return read(r)
        except urllib.error.HTTPError:
            raise
        except (TimeoutError, ConnectionError, urllib.error.URLError) as e:
            if attempt == RETRIES - 1:
                raise
            wait = 2 ** attempt * 3
            print(f"  retry  {req.full_url[:70]} in {wait}s ({e})", file=sys.stderr)
            time.sleep(wait)


def get(url, referer=None):
    headers = {"User-Agent": UA, "Accept-Language": "en-US,en"}
    if referer:
        headers["Referer"] = referer
    req = urllib.request.Request(url, headers=headers)
    return fetch(req, lambda r: r.read().decode("utf-8"))


def post(url, body, origin):
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(), method="POST",
        headers={"User-Agent": UA, "Content-Type": "application/json", "Origin": origin})
    return fetch(req, json.load)


def web_browse(body):
    return post("https://www.youtube.com/youtubei/v1/browse?prettyPrint=false",
                {"context": {"client": WEB}, **body}, "https://www.youtube.com")


def music_browse(body):
    return post("https://music.youtube.com/youtubei/v1/browse?prettyPrint=false",
                {"context": {"client": REMIX}, **body}, "https://music.youtube.com")


def embeds(pid):
    """What the embedded player says when /music/ loads this playlist."""
    try:
        html = get(EMBED + urllib.parse.quote(pid), referer=SITE)
    except urllib.error.HTTPError:
        return "HTTP_ERROR"
    return embed_status(html)


# --- parsing (pure; tested) -------------------------------------------------

def embed_status(html):
    """previewPlayabilityStatus of an embed page: "OK" if the first track
    plays, "UNPLAYABLE" for a rights block or a removed video. The page
    carries its player config as escaped JSON inside a script string."""
    m = re.search(r'previewPlayabilityStatus\\*"\s*:\s*\{\\*"status\\*"\s*:\s*\\*"([A-Z_]+)', html)
    return m.group(1) if m else "UNKNOWN"

def initial_data(html):
    m = re.search(r"var ytInitialData = (\{.*?\});</script>", html, re.S)
    if not m:
        raise ValueError("no ytInitialData on the page")
    return json.loads(m.group(1))


def walk(o, key):
    """Every value stored under `key`, anywhere in a nested JSON value."""
    if isinstance(o, dict):
        for k, v in o.items():
            if k == key:
                yield v
            yield from walk(v, key)
    elif isinstance(o, list):
        for v in o:
            yield from walk(v, key)


def text(t):
    if not isinstance(t, dict):
        return ""
    if "runs" in t:
        return "".join(r.get("text", "") for r in t["runs"])
    return t.get("simpleText") or t.get("content") or ""


def continuation(data):
    for c in walk(data, "continuationCommand"):
        if c.get("token"):
            return c["token"]
    for c in walk(data, "nextContinuationData"):
        if c.get("continuation"):
            return c["continuation"]
    return None


def channel_playlists(data):
    """(id, title) of each playlist on a channel's Playlists tab page."""
    out = []
    for l in walk(data, "lockupViewModel"):
        if l.get("contentType") not in (None, "LOCKUP_CONTENT_TYPE_PLAYLIST"):
            continue
        title = text(l.get("metadata", {}).get("lockupMetadataViewModel", {}).get("title"))
        if l.get("contentId"):
            out.append((l["contentId"], title))
    for g in walk(data, "gridPlaylistRenderer"):
        out.append((g["playlistId"], text(g.get("title"))))
    return out


def artists_of(item):
    """Artist names of one musicResponsiveListItemRenderer."""
    cols = item.get("flexColumns", [])
    if len(cols) < 2:
        return []
    runs = cols[1].get("musicResponsiveListItemFlexColumnRenderer", {}).get("text", {}).get("runs", [])
    linked = [r["text"] for r in runs
              if r.get("navigationEndpoint", {}).get("browseEndpoint", {})
              .get("browseEndpointContextSupportedConfigs", {})
              .get("browseEndpointContextMusicConfig", {})
              .get("pageType") == "MUSIC_PAGE_TYPE_ARTIST"]
    if linked:
        return linked
    # An uploaded video, not a catalogue track: column 2 is the channel.
    name = re.sub(r"(\s*-\s*Topic|VEVO)$", "", "".join(r["text"] for r in runs)).strip()
    return [name] if name else []


def tracks(data):
    """(videoId, [artists]) of each track in a YouTube Music playlist page."""
    out = []
    for item in walk(data, "musicResponsiveListItemRenderer"):
        vid = next((w["videoId"] for w in walk(item, "watchEndpoint") if w.get("videoId")), None)
        if not vid:
            vid = item.get("playlistItemData", {}).get("videoId")
        if vid:
            out.append((vid, artists_of(item)))
    return out


def header(data):
    """(title, owner, track count) from a YouTube Music playlist page."""
    for key in ("musicResponsiveHeaderRenderer", "musicDetailHeaderRenderer",
                "musicEditablePlaylistDetailHeaderRenderer"):
        for h in walk(data, key):
            title = text(h.get("title"))
            face = h.get("facepile", {}).get("avatarStackViewModel", {}).get("text")
            owner = text(face) or text(h.get("straplineTextOne"))
            m = re.search(r"([\d,]+) (?:tracks|songs)", text(h.get("secondSubtitle")) + " " + text(h.get("subtitle")))
            if title:
                return title, owner, int(m.group(1).replace(",", "")) if m else None
    return None, None, None


def top_artists(track_lists, n):
    """Tracks counted and the n most frequent artists. A song on two
    playlists counts twice: that is how often it gets played."""
    total, counts = 0, collections.Counter()
    for tl in track_lists:
        for _vid, names in tl:
            total += 1
            for a in dict.fromkeys(names):
                counts[a] += 1
    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0].lower()))
    return total, [{"name": a, "count": c} for a, c in ranked[:n]]


def listed_ids(yaml_text):
    return set(re.findall(r'^\s+id: "([^"]+)"', yaml_text, re.M))


def vanished(old, new):
    """Share of the playlists listed in `old` that `new` no longer lists."""
    before = listed_ids(old)
    return len(before - listed_ids(new)) / len(before) if before else 0.0


def q(s):
    return json.dumps(s, ensure_ascii=False)


def to_yaml(tracks_counted, artists, mine, saved):
    lines = [HEADER, "", f"tracks_counted: {tracks_counted}", "top_artists:"]
    for a in artists:
        lines += [f"  - name: {q(a['name'])}", f"    count: {a['count']}"]
    lines += ["", "mine:"]
    for p in mine:
        lines += [f"  - title: {q(p['title'])}", f"    id: {q(p['id'])}", f"    tracks: {p['tracks']}"]
        if p.get("note_key"):
            lines.append(f"    note_key: {q(p['note_key'])}")
    lines += ["", "saved:"]
    for p in saved:
        lines += [f"  - title: {q(p['title'])}", f"    id: {q(p['id'])}",
                  f"    by: {q(p['by'])}", f"    tracks: {p['tracks']}"]
    return "\n".join(lines) + "\n"


# --- fetching ----------------------------------------------------------------

def fetch_channel(handle):
    data = initial_data(get(f"https://www.youtube.com/{handle}/playlists"))
    found = channel_playlists(data)
    token, pages = continuation(data), 0
    while token and pages < MAX_PAGES:
        more = web_browse({"continuation": token})
        found += channel_playlists(more)
        token, pages = continuation(more), pages + 1
    return list(dict.fromkeys(found))


def fetch_playlist(pid):
    """Title, owner, count and tracks, or None if a stranger can't open it."""
    try:
        data = music_browse({"browseId": "VL" + pid})
    except urllib.error.HTTPError:
        return None
    title, owner, count = header(data)
    if not title:
        return None
    tl = tracks(data)
    token, pages = continuation(data), 0
    while token and pages < MAX_PAGES:
        more = music_browse({"continuation": token})
        tl += tracks(more)
        token, pages = continuation(more), pages + 1
    return {"id": pid, "title": title, "by": owner, "tracks": count or len(tl), "list": tl}


def playable(p):
    return bool(p and p["list"] and embeds(p["id"]) == "OK")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dry-run", action="store_true", help="print the result instead of writing it")
    ap.add_argument("--force", action="store_true", help="write even if many listed playlists vanished")
    args = ap.parse_args()
    cfg = json.loads(CONFIG.read_text())

    mine, skipped = [], []
    for pid, title in fetch_channel(cfg["channel"]):
        if pid in cfg["exclude"]:
            skipped.append(f"{title} (excluded in config)")
            continue
        p = fetch_playlist(pid)
        if not playable(p):
            skipped.append(f"{title} (not playable by a stranger)")
            continue
        p["note_key"] = cfg["note_keys"].get(pid)
        mine.append(p)
    mine.sort(key=lambda p: (-p["tracks"], p["title"].lower()))

    saved = []
    for pid in cfg["saved"]:
        p = fetch_playlist(pid)
        if playable(p):
            saved.append(p)
        else:
            skipped.append(f"saved {pid} (not playable by a stranger)")
    saved.sort(key=lambda p: -p["tracks"])

    if not mine:
        sys.exit("no playable playlists found on the channel -- refusing to write an empty page")

    counted, artists = top_artists([p["list"] for p in mine], cfg["top_artists"])
    out = to_yaml(counted, artists, mine, saved)

    for p in mine:
        print(f"  mine   {p['tracks']:4d}  {p['title']}" + ("" if p["note_key"] else "   (no note)"))
    for p in saved:
        print(f"  saved  {p['tracks']:4d}  {p['title']} -- {p['by']}")
    for s in skipped:
        print(f"  skip   {s}")
    print(f"  {counted} tracks; top artist {artists[0]['name']} ({artists[0]['count']})")

    if args.dry_run:
        return
    old = OUT.read_text() if OUT.exists() else ""
    lost = vanished(old, out)
    if lost > MAX_LOSS and not args.force:
        sys.exit(f"{lost:.0%} of the listed playlists vanished -- likely a partial answer "
                 "from YouTube, so nothing was written (--force if it is real)")
    if old == out:
        print("data/music.yaml unchanged")
        return
    OUT.write_text(out)
    print("wrote data/music.yaml")


if __name__ == "__main__":
    main()
