"""Picks to live: re-screen, encode, upload, write data/photos.yaml.

The encode is igmedia/derive.py, the same one Instagram media goes through,
so Google Photos originals come out the same way: capped at 1600px, every
scrap of metadata (GPS included) stripped, square grid tiles, and music added
to a silent clip.

A video is screened again from the 1080p copy it is published from, with
more frames: the picker only saw six frames of a 360p rendition, and a number
plate too small to read there can be legible at full size.
"""

import hashlib
from dataclasses import dataclass
from pathlib import Path

import yaml

from . import derive, fetch, screen

HEADER = """\
# Generated by the Google Photos picker (make media-picker) from picks.yaml —
# do not edit by hand. No captions, places or people: only the media.
"""


@dataclass
class Media:
    """What derive.derive needs to know about a source file."""

    kind: str
    path: Path
    sha256: str


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def rescreen(path: Path, kind: str, tier: str, vision, workdir: Path) -> dict:
    if kind == "video":
        images = fetch.frames(path, workdir / "frames-full" / path.stem, count=10)
    else:
        images = [path]
    return screen.verdict(vision(images), tier)


def entry(cand: dict, category: str, d: "derive.Derived") -> dict:
    media = {"kind": d.kind, "src": d.key, "thumb": d.thumb_key, "w": d.width, "h": d.height}
    if d.kind == "video":
        media["poster"] = d.poster_key
        media["duration"] = d.duration
    if d.grid_keys:
        media["grid"] = list(d.grid_keys)
    if d.color:
        media["color"] = d.color
    if d.music:
        media["music"] = d.music
    date = (cand.get("taken") or "")[:10]
    return {"id": cand["id"], "date": date, "year": date[:4], "category": category,
            "kind": d.kind, "media": [media]}


def order(entries: list[dict], categories: list[str]) -> list[dict]:
    """Category order from config, newest first inside each — the order the
    page shows them in, which is also the order the viewer pages through."""
    rank = {k: i for i, k in enumerate(categories)}
    return sorted(entries, key=lambda e: (rank.get(e["category"], 99), _neg(e["date"]), e["id"]))


def _neg(date: str) -> str:
    return "".join(chr(0x7F - ord(c)) for c in date)


def write(path: Path, base_url: str, categories: list[str], entries: list[dict]) -> None:
    present = [c for c in categories if any(e["category"] == c for e in entries)]
    payload = {"base_url": base_url.rstrip("/") + "/", "count": len(entries),
               "categories": present, "items": order(entries, categories)}
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")


class MissingSource(RuntimeError):
    pass


def build(picks: dict, cands: dict, categories: list[str], workdir: Path, prefix: str,
          lock: "derive.Lock", vision, source, log=print) -> tuple[list[dict], list[str]]:
    """Derive every included pick. Returns (entries, keys refused on re-screen).

    source(candidate) is the file to publish from: the 1600px photo or the
    1080p video the browser downloaded. Every one must be on disk first.
    """
    outdir = workdir / "web"
    entries, refused = [], []
    included = [(k, p) for k, p in picks.items() if p.get("decision") == "include"]
    missing = [k for k, _ in included if k in cands and not source(cands[k]).exists()]
    if missing:
        raise MissingSource(f"{len(missing)} included item(s) not downloaded yet — click "
                            "\"Send to picker\" on any Google Photos tab, then publish again")
    for n, (key, pick) in enumerate(included, 1):
        cand = cands.get(key)
        if not cand:
            log(f"[{n}/{len(included)}] {key[:16]}… not in candidates — harvest again; kept as is")
            continue
        path = source(cand)
        digest = sha256(path)
        cached = lock.get(digest)
        if cached is None:
            v = rescreen(path, cand["kind"], cand.get("tier", "me"), vision, workdir)
            if v["status"] == "blocked":
                log(f"[{n}/{len(included)}] {cand['id']} refused at full size: {'; '.join(v['reasons'])}")
                refused.append(key)
                continue
        d = derive.derive(Media(cand["kind"], path, digest), cand["id"], outdir, prefix, lock)
        entries.append(entry(cand, pick["category"], d))
        log(f"[{n}/{len(included)}] {cand['id']} {pick['category']} ok")
    lock.save()
    return entries, refused
