"""The approve list.

Nothing reaches the site until a human flips `approved: true` here, so the
manifest is the one file in this tool that is meant to be hand-edited. It is
committed: it is the record of what was decided, and it keeps the decision
from being lost when the next export arrives.
"""

from pathlib import Path

import yaml

HEADER = """\
# Approve list for /media/. Generated by tools/instagram-media/pull.py, then
# edited by hand: set `approved: true` on anything that should be public.
#
# Items keep their approval across re-exports because the id is derived from
# the media's own bytes. New items always arrive as approved: false.
"""


def load(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    items = data.get("items") or []
    return {i["id"]: i for i in items if isinstance(i, dict) and i.get("id")}


def merge(items, existing: dict[str, dict]) -> list[dict]:
    """Fold freshly-read export items into the decisions already made."""
    records = []
    for item in items:
        prior = existing.get(item.id, {})
        records.append({
            "id": item.id,
            "date": item.date,
            "kind": item.kind,
            "count": len(item.media),
            "approved": bool(prior.get("approved", False)),
            "caption": item.caption,
        })
    return records


def save(path: Path, records: list[dict]) -> None:
    body = yaml.safe_dump(
        {"items": records},
        sort_keys=False,
        allow_unicode=True,
        width=100,
        default_flow_style=False,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")


def approved_ids(records: list[dict]) -> set[str]:
    return {r["id"] for r in records if r.get("approved")}
