"""Upload the built files and write the Hugo data file.

Uploads go through the AWS CLI rather than boto3 so this uses exactly the
credentials and SSO session the shell already has, and needs no extra Python
dependency.
"""

import subprocess
from pathlib import Path

import yaml

# Derivative names contain a content hash, so a given URL never changes
# contents and can be cached forever.
CACHE_CONTROL = "public, max-age=31536000, immutable"

HEADER = """\
# Generated by tools/instagram-media/pull.py — do not edit by hand.
# Captions come from Instagram and stay in the language they were written in;
# the page's own UI strings live in i18n/*.toml.
"""


def sync(build_dir: Path, bucket: str, prefix: str, prune: bool = False) -> str:
    """Mirror build_dir into s3://bucket/prefix and return the CLI's output."""
    if not build_dir.exists():
        raise FileNotFoundError(f"nothing built at {build_dir}")

    cmd = [
        "aws", "s3", "sync", str(build_dir), f"s3://{bucket}/{prefix}",
        # Size-only: a rebuild rewrites mtimes, but a content-hashed name
        # means same name plus same size is the same file.
        "--size-only",
        "--cache-control", CACHE_CONTROL,
        "--no-progress",
    ]
    if prune:
        cmd.append("--delete")

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"aws s3 sync failed: {proc.stderr.strip()[:800]}")
    return proc.stdout.strip()


def write_data_file(path: Path, base_url: str, entries: list[dict]) -> None:
    """Write data/media.yaml, the only thing the Hugo layout reads."""
    payload = {
        "base_url": base_url.rstrip("/") + "/",
        "count": len(entries),
        "items": entries,
    }
    body = yaml.safe_dump(
        payload, sort_keys=False, allow_unicode=True, width=100, default_flow_style=False
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")


def entry_for(item, derived_media: list) -> dict:
    """Shape one approved item the way the layout wants it."""
    media = []
    for d in derived_media:
        record = {
            "kind": d.kind,
            "src": d.key,
            "thumb": d.thumb_key,
            "w": d.width,
            "h": d.height,
        }
        if d.kind == "video":
            record["poster"] = d.poster_key
            record["duration"] = d.duration
        media.append(record)

    return {
        "id": item.id,
        "date": item.date,
        "year": item.taken_at.strftime("%Y"),
        "kind": item.kind,
        "caption": item.caption,
        "media": media,
    }
