"""Upload the built files and write the Hugo data file.

Uploads go through the AWS CLI rather than boto3 so this uses exactly the
credentials and SSO session the shell already has, and needs no extra Python
dependency.
"""

import hashlib
import json
import subprocess
import time
from pathlib import Path

import yaml

# Derivative names contain a content hash, so a given URL never changes
# contents and can be cached forever.
CACHE_CONTROL = "public, max-age=31536000, immutable"

HEADER = """\
# Generated by tools/instagram-media/pull.py — do not edit by hand.
# Captions come from Instagram and stay in the language they were written in;
# the page's own UI strings live in i18n/*.toml.
"""


class NotSignedIn(RuntimeError):
    pass


def check_credentials(bucket: str) -> None:
    """Fail before the encoding, not after it.

    Transcoding a few hundred videos takes a long while, and an expired SSO
    token would otherwise only surface at the upload — after all that work.
    """
    who = subprocess.run(
        ["aws", "sts", "get-caller-identity", "--query", "Arn", "--output", "text"],
        capture_output=True, text=True,
    )
    if who.returncode != 0:
        detail = who.stderr.strip().splitlines()[-1] if who.stderr.strip() else "no detail"
        raise NotSignedIn(f"AWS CLI is not signed in ({detail}). Run: aws sso login")

    # Being signed in is not the same as being able to write here.
    head = subprocess.run(
        ["aws", "s3api", "head-bucket", "--bucket", bucket],
        capture_output=True, text=True,
    )
    if head.returncode != 0:
        detail = head.stderr.strip().splitlines()[-1] if head.stderr.strip() else "no detail"
        raise NotSignedIn(f"cannot reach s3://{bucket} as {who.stdout.strip()}: {detail}")


def sync(build_dir: Path, bucket: str, prefix: str, prune: bool = False) -> str:
    """Mirror build_dir into s3://bucket/prefix and return the CLI's output."""
    if not build_dir.exists():
        raise FileNotFoundError(f"nothing built at {build_dir}")

    cmd = [
        "aws", "s3", "sync", str(build_dir), f"s3://{bucket}/{prefix}",
        # Size-only: a rebuild rewrites mtimes, but a content-hashed name
        # means same name plus same size is the same file.
        "--size-only",
        "--cache-control", CACHE_CONTROL,
        "--no-progress",
    ]
    if prune:
        cmd.append("--delete")

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"aws s3 sync failed: {proc.stderr.strip()[:800]}")
    return proc.stdout.strip()


def deleted_paths(sync_output: str) -> list[str]:
    """CDN paths for every object `aws s3 sync --delete` removed.

    Lines look like `delete: s3://bucket/instagram/<id>/<file>`; the path the
    CDN serves is everything after the bucket.
    """
    paths = []
    for line in sync_output.splitlines():
        line = line.strip()
        if not line.startswith("delete: s3://"):
            continue
        key = line[len("delete: s3://"):].split("/", 1)
        if len(key) == 2 and key[1]:
            paths.append("/" + key[1])
    return sorted(set(paths))


INVALIDATION_BATCH = 3000  # CloudFront's per-request limit on paths


def invalidate(distribution_id: str, paths: list[str], run=subprocess.run) -> int:
    """Evict deleted objects from the CDN. Returns how many requests were made.

    Every derivative is cached for a year and marked immutable, so deleting an
    un-approved photo from S3 is not enough: CloudFront would keep serving it
    from the edge. Removal has to reach the cache too.
    """
    if not paths:
        return 0
    requests = 0
    for start in range(0, len(paths), INVALIDATION_BATCH):
        batch = paths[start:start + INVALIDATION_BATCH]
        # Unique per request, deliberately not derived from the paths alone:
        # CloudFront treats a reused reference as already done, forever. The
        # same content-hashed file can be approved, pruned, approved and
        # pruned again, and the second eviction must still happen.
        digest = hashlib.sha256("\n".join(batch).encode()).hexdigest()[:16]
        reference = f"prune-{time.time_ns()}-{digest}"
        body = json.dumps({
            "Paths": {"Quantity": len(batch), "Items": batch},
            "CallerReference": reference,
        })
        proc = run(
            ["aws", "cloudfront", "create-invalidation",
             "--distribution-id", distribution_id, "--invalidation-batch", body],
            capture_output=True, text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(f"invalidation failed: {proc.stderr.strip()[:500]}")
        requests += 1
    return requests


def write_data_file(path: Path, base_url: str, entries: list[dict]) -> None:
    """Write data/media.yaml, the only thing the Hugo layout reads."""
    payload = {
        "base_url": base_url.rstrip("/") + "/",
        "count": len(entries),
        "items": entries,
    }
    body = yaml.safe_dump(
        payload, sort_keys=False, allow_unicode=True, width=100, default_flow_style=False
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")


def entry_for(item, derived_media: list) -> dict:
    """Shape one approved item the way the layout wants it."""
    media = []
    for d in derived_media:
        record = {
            "kind": d.kind,
            "src": d.key,
            "thumb": d.thumb_key,
            "w": d.width,
            "h": d.height,
        }
        if d.kind == "video":
            record["poster"] = d.poster_key
            record["duration"] = d.duration
        if d.grid_keys:
            record["grid"] = list(d.grid_keys)
        if d.color:
            record["color"] = d.color
        media.append(record)

    entry = {
        "id": item.id,
        "date": item.date,
        "year": item.taken_at.strftime("%Y"),
        "kind": item.kind,
        "caption": item.caption,
    }
    # Already filtered to what Instagram displays; see archive.details().
    entry.update(getattr(item, "details", None) or {})
    entry["media"] = media
    return entry
