"""Commit and push what publish produced, and nothing else.

The site deploys from main, and the repo rule is to commit and push straight
after a change — but also to commit only the files that belong to it. So this
commits exactly the data file and the approve list by path, leaving anything
else that happens to be staged or modified alone.
"""

import subprocess
from pathlib import Path


class ReleaseError(RuntimeError):
    pass


def _git(repo: Path, *args: str, run=subprocess.run) -> subprocess.CompletedProcess:
    return run(["git", "-C", str(repo), *args], capture_output=True, text=True)


def commit_and_push(repo: Path, paths: list[Path], message: str,
                    remote: str = "origin", branch: str = "main",
                    push: bool = True, run=subprocess.run) -> str:
    """Commit only `paths` and push. Returns the new commit's short sha, or ""
    when nothing in those paths changed."""
    rel = [str(Path(p).resolve().relative_to(repo.resolve())) for p in paths if Path(p).exists()]
    if not rel:
        raise ReleaseError("nothing to release: none of the files exist")

    add = _git(repo, "add", "--", *rel, run=run)
    if add.returncode != 0:
        raise ReleaseError(f"git add failed: {add.stderr.strip()}")

    # Nothing changed in these paths since the last release: not an error.
    if _git(repo, "diff", "--cached", "--quiet", "--", *rel, run=run).returncode == 0:
        return ""

    # A pathspec on commit takes just these files, even if something else is
    # staged — that stays staged for whoever staged it.
    commit = _git(repo, "commit", "-m", message, "--", *rel, run=run)
    if commit.returncode != 0:
        raise ReleaseError(f"git commit failed: {commit.stderr.strip() or commit.stdout.strip()}")

    sha = _git(repo, "rev-parse", "--short", "HEAD", run=run).stdout.strip()
    if push:
        pushed = _git(repo, "push", remote, f"HEAD:{branch}", run=run)
        if pushed.returncode != 0:
            raise ReleaseError(f"committed {sha} but push failed: {pushed.stderr.strip()}")
    return sha


def message_for(count: int, approved: int) -> str:
    return (f"Publish {count} item{'s' if count != 1 else ''} to /media/\n\n"
            f"Generated by tools/instagram-media/pull.py release: {approved} approved\n"
            "in the manifest, encoded, uploaded to the media CDN.\n")
